[package]
name = "dp-secrets-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
kube = "0.98.0"
k8s-openapi = { version = "0.24.0", features = ["latest"] }
serde_yml = "0.0.12"
anyhow = "1.0.95"
